import React, { createContext, useContext, useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { BrowserRouter, Link, Navigate, Route, Routes, useNavigate, useParams } from 'react-router-dom'
import { QueryClient, QueryClientProvider, useQuery } from '@tanstack/react-query'
import { useForm } from 'react-hook-form'
import { z } from 'zod'
import { zodResolver } from '@hookform/resolvers/zod'
import { Bell, CheckCircle2, ClipboardPlus, HeartHandshake, LogOut, Menu, Search, ShieldCheck, Sparkles, X } from 'lucide-react'
import './styles.css'
import './animations.css'
import './safeContact.js'
import './enhancements.js'
import { API_URL } from './config.js'

const api = async (path, options = {}) => { const token = localStorage.getItem('clf-token'); const response = await fetch(`${API_URL}${path}`, { ...options, headers: { 'Content-Type':'application/json', ...(token ? { Authorization:`Bearer ${token}` } : {}), ...options.headers } }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message || 'Something went wrong.'); return body.data }
const Auth = createContext(null); const useAuth = () => useContext(Auth)
function AuthProvider({ children }) { const [user,setUser]=useState(()=>JSON.parse(localStorage.getItem('clf-user')||'null')); const login=(data)=>{localStorage.setItem('clf-token',data.token);localStorage.setItem('clf-user',JSON.stringify(data.user));setUser(data.user)}; const logout=()=>{localStorage.removeItem('clf-token');localStorage.removeItem('clf-user');setUser(null)}; return <Auth.Provider value={{user,login,logout}}>{children}</Auth.Provider> }
function Layout({ children }) { const {user,logout}=useAuth(); const [open,setOpen]=useState(false); return <><header><Link className="brand" to="/"><span>⌕</span>Campus <b>FindIt</b></Link><button className="mobile-menu" onClick={()=>setOpen(!open)}><Menu /></button><nav className={open?'open':''}><Link to="/search">Search</Link><Link to="/report">Report item</Link>{user&&<Link to="/notifications">Notifications</Link>}{user?<><Link to="/dashboard">Dashboard</Link>{user.role==='admin'&&<Link to="/admin">Admin</Link>}<button className="nav-text" onClick={logout}><LogOut size={16}/> Log out</button></>:<Link className="button small" to="/login">Log in</Link>}</nav></header>{children}<footer><div className="brand"><span>⌕</span>Campus <b>FindIt</b></div><p>A safer, simpler way to help students get belongings home.</p></footer></> }
function App(){return <Layout><Routes><Route path="/" element={<Home/>}/><Route path="/search" element={<SearchPage/>}/><Route path="/report" element={<Protected><ReportPage/></Protected>}/><Route path="/reports/:id" element={<ReportDetails/>}/><Route path="/dashboard" element={<Protected><Dashboard/></Protected>}/><Route path="/notifications" element={<Protected><Notifications/></Protected>}/><Route path="/admin" element={<Protected admin><Admin/></Protected>}/><Route path="/login" element={<Login/>}/><Route path="/register" element={<Register/>}/><Route path="*" element={<Navigate to="/"/>}/></Routes></Layout>}
function Protected({children,admin}){const {user}=useAuth();if(!user)return <Navigate to="/login" replace/>; if(admin&&user.role!=='admin')return <Navigate to="/dashboard" replace/>; return children}
function useReports(query=''){return useQuery({queryKey:['reports',query],queryFn:()=>api(`/reports?${query}`)})}
function Home(){const {data, isLoading}=useReports('limit=6');return <main><section className="hero"><div><p className="eyebrow">ONE PLACE FOR YOUR CAMPUS</p><h1>Lost something?<br/><em>Let’s get it back.</em></h1><p>Report a lost or found item in minutes. Smart matching helps the right people find each other safely.</p><div className="actions"><Link className="button" to="/report">I lost something <span>→</span></Link><Link className="button outline" to="/report">I found something <span>→</span></Link></div></div><div className="hero-card"><Search size={70}/><div>🔍 Possible match<br/><small>Black HP Laptop · 89%</small></div><div>📍 Chemistry Laboratory</div></div></section><section className="container steps"><div><p className="eyebrow">HOW IT WORKS</p><h2>From lost to reunited.</h2></div>{[['1','Report','Describe it naturally. Our AI helps fill in the important details.'],['2','Match','We compare new reports with items already on campus.'],['3','Verify','Keep private details private while ownership is checked.'],['4','Reunite','Arrange a safe collection through campus security.']].map(([n,t,d])=><article key={n}><b>{n}</b><h3>{t}</h3><p>{d}</p></article>)}</section><section className="soft"><div className="container heading"><div><p className="eyebrow">COMMUNITY BOARD</p><h2>Recently reported items</h2></div><Link to="/search">Browse all →</Link></div><div className="container grid">{isLoading?<p>Loading reports…</p>:data?.reports.map(r=><ReportCard key={r.id} report={r}/>)}</div></section><section className="container safety"><ShieldCheck/><div><h2>Built for safe handovers</h2><p>Contact details and sensitive proof of ownership are never shown publicly. We recommend campus security for collection.</p></div></section></main>}
function ReportCard({report}){return <Link className="card" to={`/reports/${report.id}`}><div className="card-art">{report.category==='Laptop'?'💻':report.category==='Calculator'?'🧮':report.category==='Student ID'?'🪪':report.category==='Backpack'?'🎒':'📦'}</div><div className="card-body"><span className={`pill ${report.type}`}>{report.type}</span><h3>{[report.color,report.brand,report.category].filter(Boolean).join(' ')||'Reported item'}</h3><p>📍 {report.location||'Campus'}</p><small>{new Date(report.createdAt).toLocaleDateString()}</small></div></Link>}
function SearchPage(){const [query,setQuery]=useState('');const [type,setType]=useState('');const {data,isLoading,error}=useReports(new URLSearchParams({q:query,type}).toString());return <main className="container page"><p className="eyebrow">FIND AN ITEM</p><h1 className="page-title">Search lost &amp; found reports</h1><form className="searchbar" onSubmit={e=>e.preventDefault()}><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try “black HP laptop with chemistry sticker”"/><button className="button">Search</button></form><div className="filters"><button className={!type?'selected':''} onClick={()=>setType('')}>All</button><button className={type==='lost'?'selected':''} onClick={()=>setType('lost')}>Lost</button><button className={type==='found'?'selected':''} onClick={()=>setType('found')}>Found</button></div>{error&&<Notice text={error.message}/>}<div className="grid results">{isLoading?<p>Searching reports…</p>:data?.reports.length?data.reports.map(r=><ReportCard key={r.id} report={r}/>):<Empty title="No matching items found" text="Try a broader search such as “black laptop”."/>}</div></main>}
function ReportPage(){const navigate=useNavigate();const [kind,setKind]=useState('lost');const [analysis,setAnalysis]=useState(null);const [busy,setBusy]=useState(false);const {register,handleSubmit,setValue,formState:{errors}}=useForm({resolver:zodResolver(z.object({description:z.string().min(10,'Please describe the item in a little more detail.')}))});const analyze=async()=>{const description=document.querySelector('#description').value;if(description.length<3)return;setBusy(true);try{const value=await api('/ai/analyze-description',{method:'POST',body:JSON.stringify({description})});setAnalysis(value);['category','brand','color','location'].forEach(k=>value[k]&&setValue(k,value[k]));}catch(e){setAnalysis({error:e.message})}finally{setBusy(false)}};const submit=async(data)=>{try{const result=await api('/reports',{method:'POST',body:JSON.stringify({...data,type:kind,keywords:analysis?.keywords||[],distinguishingFeatures:analysis?.distinguishingFeatures||[]})});navigate(`/reports/${result.id}`)}catch(e){alert(e.message)}};return <main className="container page narrow"><p className="eyebrow">NEW REPORT</p><h1 className="page-title">What happened?</h1><div className="choice"><button className={kind==='lost'?'selected':''} onClick={()=>setKind('lost')}>I lost something</button><button className={kind==='found'?'selected':''} onClick={()=>setKind('found')}>I found something</button></div><form className="form-card" onSubmit={handleSubmit(submit)}><label>Describe what you {kind==='lost'?'lost':'found'}<textarea id="description" {...register('description')} placeholder="Black HP laptop with a chemistry sticker on the back. I think I lost it around the chemistry laboratory yesterday."/></label>{errors.description&&<small className="error">{errors.description.message}</small>}<button type="button" className="button ai" onClick={analyze} disabled={busy}><Sparkles size={17}/>{busy?'Analyzing…':'Analyze with AI'}</button>{analysis&&!analysis.error&&<div className="analysis"><b>AI understood — you can edit any of this</b><div className="form-grid"><Input label="Category" name="category" register={register}/><Input label="Brand" name="brand" register={register}/><Input label="Color" name="color" register={register}/><Input label="Location" name="location" register={register}/></div>{analysis.distinguishingFeatures?.length>0&&<p>Noted features: {analysis.distinguishingFeatures.join(', ')}</p>}</div>}<div className="form-grid"><Input label="Category" name="category" register={register}/><Input label="Brand" name="brand" register={register}/><Input label="Color" name="color" register={register}/><Input label="Location" name="location" register={register}/></div><label>Private ownership detail <input {...register('privateDetails')} placeholder="Optional — never shown publicly"/></label><button className="button submit">Submit {kind} report →</button></form></main>}
function Input({label,name,register}){return <label>{label}<input {...register(name)} placeholder={label}/></label>}
function ReportDetails(){const {id}=useParams();const {user}=useAuth();const navigate=useNavigate();const {data:report,error,isLoading}=useQuery({queryKey:['report',id],queryFn:()=>api(`/reports/${id}`)});const {data:matches}=useQuery({queryKey:['matches',id],queryFn:()=>api(`/reports/${id}/matches`),enabled:!!user});const claim=async(match)=>{const explanation=prompt('Why do you believe this item belongs to you? Include a detail the finder can verify.');if(!explanation)return;try{await api('/claims',{method:'POST',body:JSON.stringify({lostReportId:report.type==='lost'?report.id:match.report.id,foundReportId:report.type==='found'?report.id:match.report.id,ownershipExplanation:explanation})});alert('Claim submitted. The finder has been notified.');navigate('/dashboard')}catch(e){alert(e.message)}};if(isLoading)return <main className="container page">Loading report…</main>;if(error)return <main className="container page"><Notice text={error.message}/></main>;return <main className="container page detail"><div><span className={`pill ${report.type}`}>{report.type}</span><h1 className="page-title">{[report.color,report.brand,report.category].filter(Boolean).join(' ')||'Reported item'}</h1><p className="lead">{report.description}</p><dl><dt>Category</dt><dd>{report.category||'Not specified'}</dd><dt>Location</dt><dd>{report.location||'Campus'}</dd><dt>Status</dt><dd>{report.status.replace('_',' ')}</dd><dt>Reported</dt><dd>{new Date(report.createdAt).toLocaleDateString()}</dd></dl><button className="link-button" onClick={()=>user?api(`/reports/${id}/flag`,{method:'POST',body:JSON.stringify({reason:'Suspicious ownership claim'})}).then(()=>alert('Thanks. This report was flagged for review.')):navigate('/login')}>Report this listing</button></div>{user&&matches?.length>0&&<aside className="matches"><h2>Potential matches</h2>{matches.map(m=><div className="match" key={m.id}><b>{m.score}% potential match</b><h3>{[m.report.color,m.report.brand,m.report.category].filter(Boolean).join(' ')}</h3><p>{m.reasons.map(x=>'✓ '+x).join(' · ')}</p>{report.type==='lost'&&<button className="button" onClick={()=>claim(m)}>I think this is mine</button>}</div>)}</aside>}</main>}
function Dashboard(){const {user}=useAuth();const {data:reports}=useReports('');const {data:claims,refetch}=useQuery({queryKey:['claims'],queryFn:()=>api('/claims')});const mine=reports?.reports.filter(r=>r.userId===undefined) || [];return <main className="container page"><p className="eyebrow">YOUR SPACE</p><h1 className="page-title">Welcome back, {user.name.split(' ')[0]}</h1><div className="quick"><Link to="/report" className="button"><ClipboardPlus size={17}/> Report an item</Link><Link to="/notifications" className="button outline"><Bell size={17}/> Notifications</Link></div><section className="dashboard-section"><h2>Your claims</h2>{claims?.length?claims.map(c=><ClaimCard key={c.id} claim={c} refresh={refetch}/>):<Empty title="No claims yet" text="Potential matches will appear when we find them."/>}</section><section className="dashboard-section"><h2>Your reports</h2><p className="muted">Search the community board and report a new lost or found item. Your reports automatically receive matches.</p><Link className="button" to="/search">Browse reports</Link></section></main>}
function ClaimCard({claim,refresh}){const {user}=useAuth();const [message,setMessage]=useState('');const {data:messages,refetch}=useQuery({queryKey:['messages',claim.id],queryFn:()=>api(`/claims/${claim.id}/messages`)});const action=async(path,body={})=>{try{await api(`/claims/${claim.id}/${path}`,{method:'POST',body:JSON.stringify(body)});refresh();}catch(e){alert(e.message)}};return <article className="claim"><div><b className="pill found">{claim.status.replaceAll('_',' ')}</b><p>{claim.ownershipExplanation}</p>{claim.handoverCode&&<p className="code">Claim code: {claim.handoverCode}</p>}</div>{claim.finderId===user.id&&claim.status==='pending'&&<div className="actions"><button className="button" onClick={()=>action('approve',{handoverMethod:'Campus Security'})}>Approve — Campus Security</button><button className="button outline" onClick={()=>action('reject')}>Reject</button></div>}{claim.claimantId===user.id&&claim.status==='ready_for_handover'&&<button className="button" onClick={()=>action('complete')}>I received my item</button>}<div className="messages">{messages?.map(m=><p key={m.id}><b>{m.senderId===user.id?'You':'Other person'}:</b> {m.message}</p>)}<form onSubmit={async e=>{e.preventDefault();if(!message)return;await api(`/claims/${claim.id}/messages`,{method:'POST',body:JSON.stringify({message})});setMessage('');refetch()}}><input value={message} onChange={e=>setMessage(e.target.value)} placeholder="Message about safe handover"/><button>Send</button></form></div></article>}
function Notifications(){const {data,refetch}=useQuery({queryKey:['notes'],queryFn:()=>api('/notifications')});return <main className="container page"><p className="eyebrow">UPDATES</p><h1 className="page-title">Notifications</h1><button className="link-button" onClick={async()=>{await api('/notifications/read-all',{method:'PATCH'});refetch()}}>Mark all as read</button><div className="notification-list">{data?.length?data.map(n=><article className={n.read?'notification read':'notification'} key={n.id}><Bell size={18}/><div><b>{n.title}</b><p>{n.message}</p></div></article>):<Empty title="You’re all caught up" text="We’ll notify you when a potential match or claim needs attention."/>}</div></main>}
function Admin(){const {data, isLoading}=useQuery({queryKey:['admin'],queryFn:()=>api('/admin/stats')});return <main className="container page"><p className="eyebrow">ADMIN</p><h1 className="page-title">Platform overview</h1>{isLoading?<p>Loading statistics…</p>:<div className="stats">{Object.entries(data).map(([key,value])=><div className="stat" key={key}><b>{value}</b><span>{key.replace(/([A-Z])/g,' $1')}</span></div>)}</div>}<p className="muted">Admin authorization is enforced by the API. This dashboard is only visible to the seeded administrator account.</p></main>}
const credentials=z.object({email:z.string().email('Enter a valid email address.'),password:z.string().min(8,'Password needs at least 8 characters.')})
function Login(){const navigate=useNavigate(),{login}=useAuth();const {register,handleSubmit,formState:{errors,isSubmitting}}=useForm({resolver:zodResolver(credentials)});const submit=async(data)=>{try{login(await api('/auth/login',{method:'POST',body:JSON.stringify(data)}));navigate('/dashboard')}catch(e){alert(e.message)}};return <AuthPage title="Welcome back" subtitle="Log in to report items, manage claims, and see your matches."><form onSubmit={handleSubmit(submit)}><Input label="Email" name="email" register={register}/><Input label="Password" name="password" register={register}/>{Object.values(errors).map(e=><small className="error" key={e.message}>{e.message}</small>)}<button className="button submit" disabled={isSubmitting}>{isSubmitting?'Logging in…':'Log in'}</button></form><p>New here? <Link to="/register">Create an account</Link></p><p className="demo">Demo: student@example.com / finder@example.com / admin@example.com<br/>Password: Password123!</p></AuthPage>}
function Register(){const navigate=useNavigate(),{login}=useAuth();const {register,handleSubmit,formState:{isSubmitting}}=useForm();const submit=async(data)=>{try{login(await api('/auth/register',{method:'POST',body:JSON.stringify(data)}));navigate('/dashboard')}catch(e){alert(e.message)}};return <AuthPage title="Create your account" subtitle="Use your campus details so reports stay trustworthy."><form onSubmit={handleSubmit(submit)}><div className="form-grid"><Input label="Full name" name="name" register={register}/><Input label="Student ID" name="studentId" register={register}/><Input label="Email" name="email" register={register}/><Input label="Password (8+ characters)" name="password" register={register}/><Input label="Department" name="department" register={register}/><Input label="Faculty" name="faculty" register={register}/><Input label="Level" name="level" register={register}/></div><button className="button submit" disabled={isSubmitting}>{isSubmitting?'Creating…':'Create account'}</button></form><p>Already have an account? <Link to="/login">Log in</Link></p></AuthPage>}
function AuthPage({title,subtitle,children}){return <main className="auth"><div className="form-card"><p className="eyebrow">CAMPUS FINDIT</p><h1>{title}</h1><p>{subtitle}</p>{children}</div></main>}
function Notice({text}){return <p className="notice">{text}</p>}function Empty({title,text}){return <div className="empty"><HeartHandshake size={30}/><h3>{title}</h3><p>{text}</p></div>}
createRoot(document.getElementById('root')).render(<React.StrictMode><QueryClientProvider client={new QueryClient()}><BrowserRouter><AuthProvider><App/></AuthProvider></BrowserRouter></QueryClientProvider></React.StrictMode>)
